baseURL = 'https://farizifs.com/'
languageCode = 'en-us'
title = 'Farizi`s Blog'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Personal and Professional Blog"

# Appearance settings
theme = 'light'
colorPalette = 'eink'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Welcome!'
homeIntroContent = """
Welcome to my corner of the web! 

This blog is my space for sharing IT projects, ideas, and the occasional deep dive into life's curiosities.

Feel free to drop me a line at farizi@tuta.io. Cheers!"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/farizifatwa/"

[[params.social]]
name = "github"
url = "https://github.com/farizif"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "books"
url = "/books"

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "lfs3"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://farizifs.com?region=us-east-1"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'trac'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"